Full page localisation
elixirschool/school_house pull request #192
Opened 2022-05-14 18:24 UTC by tenshikiri

- [ ] Added missing gettext on {hopefully} all text that was missing one
- [ ] Generated .po files for all languages except zh-hans & zh-hant

2022-05-14 21:29 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Συμπεριφορές"
Σετ αλλαγών

2022-05-14 21:31 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr ""
what the???

2022-05-14 21:32 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Απο"
Από

2022-05-14 21:34 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Με την εξάλειψη της δυνατότητας μετάλλαξης κατάστασης εκτός του πεδίου εφαρμογής, τα λειτουργικά προγράμματα είναι συχνά πιο εύκολο να ακολουθηθούν και περιέχουν λιγότερα σφάλματα."
όχι λειτουργικά... Συναρτησιακά;

2022-05-14 21:34 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr ""
Έλεγξε όλα τα συνέδρια που εστιάζουν στην Elixir!

2022-05-14 21:35 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Δείτε όλα τα συνέδρια που επικεντρώνονται στην Elixir!"
Μάλλον το μπέρδεψες με το από πάνω ε;

2022-05-14 21:35 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Ανακαλύψτε γιατί η δημοτικότητα της Elixir έχει εκτοξευθεί και νέες εταιρείες την υιοθετούν καθημερινά."
Πιο πάνω το έχεις εταιρία. και τα δύο σωστά είναι, απλά διάλεξε ένα

2022-05-14 21:37 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Λειτουργικός Προγραμματισμός"
Συναρτησιακός Προγραμματισμός

2022-05-14 21:37 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Η αλληλεπίδραση με δεδομένα είναι μέρος των περισσότερων εφαρμογών. Αυτά τα μαθήματα εξερευνούν τη βιβλιοθήκη Ecto και πώς να την αξιοποιήσουμε για τις αλληλεπιδράσεις με τη βάση δεδομένων μα
πως χωρίς τόνο

2022-05-14 21:38 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Πολιτική Απορρήτου."
αφαίρεσε το και βάλε χωρίς την τελεία

2022-05-14 21:42 UTC, gemantzu requested changes
A-we-so-me @tenshikiri ! We needed this. Just some changes related to greek translation and you are good to go

2022-05-15 06:46 UTC, tenshikiri commented
> A-we-so-me @tenshikiri ! We needed this. Just some changes related to greek translation and you are good to go

Fixed, I was expecting more :D

2022-05-15 18:37 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Η ίδια η φύση του συναρτησιακού προγραμματισμού, οι μικρές λειτουργίες χωρίς παρενέργειες, κάνουν τη δοκιμή εύκολη."
Οι μικρές συναρτήσεις

2022-05-15 18:38 UTC, gemantzu commented on priv/gettext/el/LC_MESSAGES/default.po
> +msgstr "Περισσότερα ακολουθούν..."
Ακολουθούν περισσότερα...

2022-05-15 19:23 UTC, gemantzu approved these changes
Thank you @tenshikiri ! @doomspork please take a look, looks good to me. It's a good initiative to have complete translation on the website.

2022-05-16 12:31 UTC, doomspork approved these changes
@tenshikiri this is _amazing_ thank you so much! 🚀

2022-05-16 12:37 UTC, merged